const colors = {
  light: {
    text: "#ffffff",
    tint: "#ff3b30",
    background: "#0d0d0d",
    foreground: "#ffffff",
    card: "#1c1c1e",
    cardForeground: "#ffffff",
    primary: "#ff3b30",
    primaryForeground: "#ffffff",
    secondary: "#2c2c2e",
    secondaryForeground: "#ebebf5",
    muted: "#2c2c2e",
    mutedForeground: "#8e8e93",
    accent: "#ff3b30",
    accentForeground: "#ffffff",
    destructive: "#ff453a",
    destructiveForeground: "#ffffff",
    border: "#38383a",
    input: "#38383a",
  },
  dark: {
    text: "#ffffff",
    tint: "#ff3b30",
    background: "#0d0d0d",
    foreground: "#ffffff",
    card: "#1c1c1e",
    cardForeground: "#ffffff",
    primary: "#ff3b30",
    primaryForeground: "#ffffff",
    secondary: "#2c2c2e",
    secondaryForeground: "#ebebf5",
    muted: "#2c2c2e",
    mutedForeground: "#8e8e93",
    accent: "#ff3b30",
    accentForeground: "#ffffff",
    destructive: "#ff453a",
    destructiveForeground: "#ffffff",
    border: "#38383a",
    input: "#38383a",
  },
  radius: 16,
};

export default colors;
